language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn compile
  - yarn test
script:
  - yarn sass
  - mkdir gh-pages
  - yarn doc:github
  - yarn doc:pokemon
  # - yarn doc:scaphold
  - yarn doc:shopify
  - yarn doc:starwars-js
  - yarn doc:starwars
