language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g jest
before_script:
  - npm prune --production
  # - mkdir gh-pages
  # - npm run doc.github
  # - npm run doc.shopify
  # - npm run doc.starwars-js
  # - npm run doc.starwars
  # - npm run doc.scaphold
script:
  - npm run compile
  - npm test
